# -*- coding: utf-8 -*-
"""CE101-Cleaned-Data-Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bqlkQFdmj9qB0QVgsZ6JBXg74iUfzkF1
"""

from google.colab import drive

import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.offline as py

import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/CE101 Team Project/cleaned_heart_data.csv')

data.head()

data.isnull().sum()

data = data.rename(columns={'cp': 'Chest Pain Type', 'trestbps': 'Resting Blood Pressure (mm/Hg)', 'chol' : 'Serum Cholrestoral (mg/dl)', 'fbs' : 'Fasting blood sugar' })

data.head()

data = data.rename(columns={'restecg': 'Resting ECG', 'thalach': 'MAX Heartrate', 'exang' : 'Exercice Induced Angina', 'ca' : 'number of major vessels'})

data.tail()

display(data)

data.describe()

data['age'].hist(grid=True, bins=10);
plt.title('Age distribuition')

filename = ('/content/drive/MyDrive/CE101 Team Project/heart.csv')

data.to_csv(filename)