# -*- coding: utf-8 -*-
"""groupby.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QReKuDFiJTMe-GaFhqzUogx2CNe3xN6_
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv('heart.csv')
df.head()

df.shape

df.info()

df['target'].value_counts()

df.describe()

df.corr()['target'].sort_values(ascending=True)

X = df.drop('target', axis=1)
y = df['target']

X.shape

y.shape

from sklearn.model_selection import train_test_split

X_temp, X_test, y_temp, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

X_train, X_val, y_train, y_val = train_test_split(
    X_temp, y_temp,
    test_size=0.25,
    random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train_scaled, y_train)

from sklearn.metrics import accuracy_score

val_preds = log_reg.predict(X_val_scaled)
accuracy_score(y_val, val_preds)

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)

knn_preds = knn.predict(X_val_scaled)
accuracy_score(y_val, knn_preds)